### ISSUE TITLE
Error when there are no AppSettings yet

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#285] opened 2017-03-16 12:19 UTC
```
'NoneType' object has no attribute 'wifi_only_downloads'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/restapi.py", line 134, in get
    result = self.run(f, kwargs, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/restapi.py", line 174, in run
    result = run(f, kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/rpc.py", line 165, in run
    result = function(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/restapi.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/solutions/common/restapi/cityapp.py", line 50, in rest_get_app_settings
    return app.get_settings()
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/rogerthat/rpc/service.py", line 337, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/rogerthat/service/api/app.py", line 201, in get_settings
    return AppSettingsTO.from_model(bizz_app.get_app_settings(app_id))
  File "/base/data/home/apps/s~mobicagecloudhr/29.399831408309452127/rogerthat/to/app.py", line 185, in from_model
    return cls(model.wifi_only_downloads, model.background_fetch_timestamps, model.oauth,
AttributeError: 'NoneType' object has no attribute 'wifi_only_downloads'
```

Happened for new app: be-geetbets

**Comment by siddiquagig** [comment] 2017-03-23 07:07
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the status_resolved label and close the issue.

Thanks!

**Comment by bart-at-mobicage** [comment] 2017-04-27 09:33
A second occurrence. Let's lazily create an AppSettings instance if it doesn't exist yet.

```
10:37:32.552
Queue: fast
deferred.run(shop.bizz._after_service_saved,
             datastore_types.Key.from_path(u'Customer', 6446981898567680L, _app=u's~mobicagecloudhr'),
             u'***@***.be',
             <solutions.common.to.ProvisionResponseTO object at 0xf6ad2250>,
             False,
             [u'be-***', u'rogerthat'],
             [users.User(email='roel@mobicage.com',_user_id='117463801899886690355')])

10:37:32.617
'NoneType' object has no attribute 'birthday_message'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/add_1_monkey_patches.py", line 283, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/shop/bizz.py", line 790, in _after_service_saved
    run_in_xg_transaction(trans)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/48.400715093888759503/shop/bizz.py", line 742, in trans
    u'birthday_message_default_text')
AttributeError: 'NoneType' object has no attribute 'birthday_message'
```

**Comment by bart-at-mobicage** [comment] 2017-04-27 09:53
Will be fixed when 
- there's a main service set
- we use GIG Mobile Control Center to create new apps

**Comment by lucasvanhalst** [comment] 2017-04-27 11:58
Make migration which:
- creates an appsettings model for every app if it doesn't exist yet
- sets the oauth settings to an empty property

**Closed** 2017-05-02 10:23 UTC
Labels: type_bug
