### ISSUE TITLE
Salutation Associations

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#176] opened 2017-01-10 09:30 UTC
Please make possible that when customers ask a question in an application of an association do not be addressed as "dear Customer" but as " Shoot your question and we will answer"

Thanks

**Comment by RubenMattan** [comment] 2017-01-20 12:08
Make it possible to configure this in the dashboard

**Comment by lucasvanhalst** [comment] 2017-01-20 12:27
duplicate of #156

**Closed by lucasvanhalst** 2017-01-20 12:27 UTC
Labels: type_feature
