### ISSUE TITLE
Failed to provision service

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#90] opened 2016-11-21 14:17 UTC
```python
14:13:33.721
Failure in common_provision
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/solutions/common/bizz/__init__.py", line 571, in common_provision
    bizz.provision(service_user)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/solutions/flex/bizz.py", line 120, in provision
    allow_transaction_propagation(db.run_in_transaction_options, xg_on, provision_all_modules, sln_settings, DEFAULT_COORDS, main_branding, default_lang)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/add_1_monkey_patches.py", line 205, in _allow_transaction_propagation
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/add_1_monkey_patches.py", line 184, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/add_1_monkey_patches.py", line 166, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/solutions/common/bizz/provisioning.py", line 660, in provision_all_modules
    POKE_TAGS[module])
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/solutions/common/bizz/provisioning.py", line 1604, in put_when_where
    when_where_branding = generate_branding(main_branding, u'when_where', content, [map_png])
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/solutions/common/bizz/system.py", line 56, in generate_branding
    return store_branding(description, base64.b64encode(new_zip_stream.getvalue()))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/rogerthat/rpc/service.py", line 312, in wrapped
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/rogerthat/service/api/system.py", line 160, in store_branding
    return BrandingTO.fromDBBranding(store_branding_bizz(service, zip_stream, description))
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/rogerthat/bizz/branding.py", line 310, in store_branding
    return store_branding_zip(service_user, zip_, description)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 149, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/mcfw/rpc.py", line 127, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/1.397211539624869187/rogerthat/bizz/branding.py", line 383, in store_branding_zip
    b = Branding.get_by_key_name(hash_)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1282, in get_by_key_name
    return get(keys[0], **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1540, in get
    return get_async(keys, **kwargs).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1648, in __get_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1371, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: operating on too many entity groups in a single transaction.
```

**Comment by siddiquagig** [comment] 2017-03-23 07:49
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2017-10-05 09:23 UTC
Labels: type_bug
