### ISSUE TITLE
OSA Terminal: Show the discount when loyalty card is redeemed

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#61] opened 2016-11-10 14:52 UTC

**Comment by siddiquagig** [comment] 2017-03-23 07:50
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2018-01-24 09:07 UTC
