### ISSUE TITLE
Cannot post news in em-be-threefold-token

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#950] opened 2018-06-08 11:29 UTC
![2018-06-08 13](https://user-images.githubusercontent.com/17762105/41155686-3fdbd19e-6b1f-11e8-9357-0b3fa7cc1b3a.jpg)

`app_ids` is empty

service = `service-4bf3bdf1-8628-491d-849b-698d7503c68a@rogerth.at`
supported apps = `em-be-threefold-token`

`[XX-OFFLOADv1]{"function":"/common/news","status":true,"request_data":{"broadcast_on_facebook":false,"title":"*****","image":"*****","tag":"news","order_items":[],"broadcast_on_twitter":false,"broadcast_type":"News","role_ids":[...],"app_ids":[],"message":"*****","type":1},"timestamp":1528449714.7334099,"response_data":"****","type":"web","user":"5c31adac01cad92a435c44f514798d88"}`

**Comment by abom** [comment] 2018-06-10 12:08
The problem is that cities map is enabled, and the app name is not a city itself. So when getting selected apps/cities from the map, it gives an empty list.

Now this service has two apps that don't have the name of a city, should we just select them by default or add another method to select non-city apps?

**Comment by abom** [comment] 2018-06-11 10:03
According to the changes in #955, local news (current active apps of the service) will be mandatory and cannot be unset.

So, we should select all available for a service by default.

**Comment by bart-at-mobicage** [comment] 2018-06-11 10:23
I don't know yet which logic we would add best in this case.

Services in apps like be-fairphone, be-foxtown, em-be-threefold-token, em-be-threefold-staging, ... shouldn't be able to post in regional news. They're actually enterprise apps, but the app's type is set to CITY_APP so we can (ab)use the shop for this.

Quick workaround could be to change the country of the threefold service to Dubai. But that won't solve the underlying issue.

**Comment by abom** [comment] 2018-06-11 10:34
But for actual city apps, we should select all the app of the service by default (as local news), and allow to select other city apps? and in this case, a merchant for example cannot deselect his own city (default app).

**Comment by lucasvanhalst** [comment] 2018-06-19 07:47
Sort off fixed now with the checkboxes, but we'll have to change it so it doesn't show the checkboxes at all when the app's type != city app.

**Closed** 2018-06-19 08:56 UTC
Labels: priority_major, state_verification, type_bug
