### ISSUE TITLE
send_conversation failed message not in list

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#1214] opened 2019-01-24 08:02 UTC
```
deferred.run(rogerthat.bizz.messaging._send_conversation,
             users.User(email='***:be-hooglede'),
             u'c72cfb8e-85e3-4200-b281-226ad06fbb31',
             False,
             u'e9ac2755-aae0-464c-922d-a4a14bdc543e')


 File "rogerthat/bizz/messaging.py", line 2772, in trans
    offset_index = parent_message.childMessages.index(get_message_key(offset, parent_message_key))
ValueError: datastore_types.Key.from_path(u'Message', u'c72cfb8e-85e3-4200-b281-226ad06fbb31', u'Message', u'e9ac2755-aae0-464c-922d-a4a14bdc543e', _app=u'e~rogerthat-server') is not in list
```

**Comment by lucasvanhalst** [comment] 2019-01-25 09:36
It was caused by the error fixed by https://github.com/our-city-app/mobicage-backend/pull/150

**Closed by lucasvanhalst** 2019-01-25 09:36 UTC
Labels: priority_minor, type_bug
