### ISSUE TITLE
channel not reconnecting?

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#175] opened 2017-01-09 14:18 UTC
Seen this at the development environment and on the tablets of the sales ppl.

When a service is being created a progress bar is shown, but never goes away. It looks like the channel gets disconnected, but doesnt automatically reconnect.

**Comment by siddiquagig** [comment] 2017-03-23 06:40
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-04-06 09:06
will be fixed by implementing new channel https://github.com/rogerthat-platform/rogerthat-backend/issues/49

**Closed by RubenMattan** 2017-04-06 09:06 UTC
Labels: priority_critical, process_wontfix, type_bug
