### ISSUE TITLE
Not possible to change from simple to advanced order in services in the city dashboard

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#600] opened 2017-10-13 12:26 UTC
![image 2017-10-13 14 25 52](https://user-images.githubusercontent.com/26439611/31546149-6bc9691e-b022-11e7-8b44-7a99e18f02a6.jpg)
![image 2017-10-13 14 25 56](https://user-images.githubusercontent.com/26439611/31546152-6e0c7220-b022-11e7-8060-c449bf89d7f6.jpg)

**Comment by RubenMattan** [comment] 2017-10-17 10:34
@stevendepaepe Can u provide me with some service info

**Comment by RubenMattan** [comment] 2017-10-17 10:35
Tested locally and did not have this issue

**Comment by RubenMattan** [comment] 2017-10-17 10:37
duplicate of https://github.com/our-city-app/oca-backend/issues/580

**Comment by bart-at-mobicage** [comment] 2017-10-17 10:53
When a city logs in to a merchant dashboard from their own dashboard, then they can not configure advanced order

**Comment by RubenMattan** [comment] 2017-10-17 10:56
Services should not be able to change this!

**Closed** 2017-10-18 15:22 UTC
Labels: priority_major, state_verification, type_bug
