### ISSUE TITLE
Removing buttons with a setup by a third party

### ISSUE THREAD

**Issue by AnthonyMaes** [our-city-app/oca-backend#287] opened 2017-03-16 13:33 UTC
A government or a third party is now able to do the setup of an application for a local merchant or association. Within these setup versions, better to unable the buttons "app users and roles" and "inbox". (circles in red screenshot 2)
![screenshot 1](https://cloud.githubusercontent.com/assets/25529887/23998488/91a9f806-0a55-11e7-8a24-e0b2ecbc24b5.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/25529887/23998489/91aec606-0a55-11e7-923c-a40710b6de07.png)

**Comment by siddiquagig** [comment] 2017-03-23 06:17
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Closed** 2017-04-11 09:17 UTC
Labels: priority_major, state_verification, type_feature
