### ISSUE TITLE
Loyalty for everybody

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#163] opened 2016-12-23 08:09 UTC
OCA Loyalty-Scan should be able to scan every Qr-Code.

The goal is that OCA accepts every loyalty-card on the market with a QR-Code.

If necessary let's have a chat about this issue.

**Comment by bart-at-mobicage** [comment] 2016-12-23 10:12
duplicate of https://github.com/rogerthat-platform/rogerthat-backend/issues/43

**Closed by bart-at-mobicage** 2016-12-23 10:12 UTC
Labels: process_duplicate, type_feature
