### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#91] opened 2016-11-22 07:59 UTC
Please use the correct branding - homescreen branding (now it is the main branding and not correct)

![screenshot_20161122-085643](https://cloud.githubusercontent.com/assets/23034120/20515440/fa5cbec4-b091-11e6-9f78-45cbe547c7b0.png)

Please give a follow up message after submitting the phone number in "contact us" as following:

Please change emailadress in welcomemessage "info@mobicage.com" into "info@onzestadapp.be" for Dutch and "info@ourcityapps.com" for other languages.

Beste,

bedankt voor uw interesse.

Wij hebben uw informatie goed ontvangen.
Wij zullen u eerstdaags contacteren.

Mvg,

Onze-Stad-App-Team

Rogerthat-knop

**Comment by siddiquagig** [comment] 2017-03-23 07:49
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Comment by bart-at-mobicage** [comment] 2017-04-14 11:47
not relevant anymore. signup procedure is changed

**Closed by bart-at-mobicage** 2017-04-14 11:47 UTC
Labels: type_bug
