### ISSUE TITLE
Appointment

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#497] opened 2017-08-29 14:23 UTC
@ this time we have no usefull appointment system.

It would be great to generate a good appointment-system.
This could be a feature they have to pay for?
But for now nobody uses the feature because not good enough.

It is crucial for certain categories by ex nail/hair/doctors/....

**Comment by RubenMattan** [comment] 2017-10-05 10:25
Duplicate of https://github.com/our-city-app/oca-backend/issues/497

**Comment by lucasvanhalst** [comment] 2017-10-06 07:34
Issue can't be duplicate of itself

**Comment by bart-at-mobicage** [comment] 2017-10-06 07:35
Duplicate of #410

**Closed by bart-at-mobicage** 2017-10-06 07:35 UTC
Labels: type_feature
