### ISSUE TITLE
Limit number of news items a day

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#126] opened 2016-12-02 08:08 UTC
A service scheduled 5 news items at the same day, hour with the same content ...

**Comment by bart-at-mobicage** [comment] 2016-12-06 09:34
Investigate if the user clicked the submit button 5 times, or if something retried in our code.

**Comment by siddiquagig** [comment] 2017-03-23 06:44
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2017-11-09 13:51 UTC
Labels: type_feature
