### ISSUE TITLE
Takeaway time for sandwiches

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#100] opened 2016-11-25 09:08 UTC
Allow specifying a takeaway time for sandwich orders in the flow

**Comment by siddiquagig** [comment] 2017-03-23 06:44
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2018-05-08 08:34 UTC
Labels: type_feature
