### ISSUE TITLE
Prices shown in menu page and loyalty page are not ljusted with "0"

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#169] opened 2016-12-29 16:06 UTC
€1 is shown instead of €1.00
€1.8 is shown instead of €1.80
...

![screen shot 2016-12-29 at 17 03 54](https://cloud.githubusercontent.com/assets/17762105/21547873/0f687c30-cde9-11e6-82fc-3c4c0d50f8d0.png)

![screen shot 2017-01-04 at 13 45 51](https://cloud.githubusercontent.com/assets/17762105/21642662/2e6d1dee-d284-11e6-82df-405700ddee49.png)

![screen shot 2017-01-04 at 13 50 56](https://cloud.githubusercontent.com/assets/17762105/21642772/ea644266-d284-11e6-93de-abd4c1c45f75.png)

**Comment by siddiquagig** [comment] 2017-03-23 06:40
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2017-05-12 07:13 UTC
Labels: state_verification, type_bug
