### ISSUE TITLE
PSP app improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1418] opened 2019-08-22 14:12 UTC
- [x] Show hamburger icon instead of back button on the app's home page
- [x] Android app doesn't render the custom psp sidebar icon
- [x] Estimate how much time would it take to add a cover picture to a merchant. Not only in the app but also on the merchant admin page. -> 1.5 days
- [x] Show an (i) button next to the project title label
- [x] When an error happens while scanning, the LOADING popup doesn't disappear and the ERROR popup is shown underneath the LOADING popup
- [x] Make sure the opening hours wrap when it doesn't fit on 1 line.
<img width="300px" src="https://user-images.githubusercontent.com/17762105/63521619-19c7c700-c4f7-11e9-9909-23c2fbd49105.jpg">

Might be better if we used tables for alignment
```
Maandag    08:15 - 12:15
           12:45 - 18:00
Dinsdag    08:15 - 12:15
           12:45 - 18:00
Woensdag   08:15 - 12:15
           12:45 - 18:00
Donderdag  08:15 - 12:15
           12:45 - 18:00
Vrijdag    08:15 - 12:15
           12:45 - 18:00
Zaterdag   08:00 - 12:00
Zondag     Gesloten
```
- [x] On Android the scroll offset is wrong after scanning when there are multiple projects
<img width="300px" src="https://user-images.githubusercontent.com/17762105/63521620-19c7c700-c4f7-11e9-9a7e-59e36503c1fd.JPG">

**Comment by lucasvanhalst** [comment] 2019-09-13 09:07
>  Show hamburger icon instead of back button on the app's home page

does android have a way to open the sidebar from an embedded app?

**Comment by lucasvanhalst** [comment] 2019-09-13 09:24
>  When an error happens while scanning, the LOADING popup doesn't disappear and the ERROR popup is shown underneath the LOADING popup

Can't reproduce, what kind of error? server error?

**Comment by lucasvanhalst** [comment] 2019-09-13 12:25
Last issue seems to be fixed by updating the libraries

**Comment by lucasvanhalst** [comment] 2019-09-13 13:29
Second issue is fixed by https://github.com/our-city-app/mobicage-android-client/pull/170

**Closed** 2019-09-20 11:30 UTC
Labels: priority_major, state_verification, type_feature
