### ISSUE TITLE
subscription extensions: extra city product should be added to invoice when extending a subscription

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#196] opened 2017-01-27 11:11 UTC
Now when a subscription extension order (with or without tablet) is made the extra cities aren't added to the invoice.

**Comment by siddiquagig** [comment] 2017-03-23 06:39
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2018-05-08 08:37 UTC
Labels: priority_major, type_bug
