### ISSUE TITLE
Birthday messages aren't sent anymore

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1252] opened 2019-03-08 18:16 UTC
- [ ] I didn't receive any birthday message, so I checked the logs and found `No default birthday branding has been set. Skipping sending out birthday messages for ...`

- [x] Also, be sure to check/test the behaviour of flag SHARED_MEMBERS. It is not set in the code, but it looks like multiple members are in my birthday message sent in 2017. See screenshot:
<img src="https://user-images.githubusercontent.com/17762105/54047040-45b7f000-41d6-11e9-92d5-bb4d8a3ccbf1.png" height="500px">

- [ ] Let's change the button caption to "Thank you" instead of "OK"

**Comment by RubenMattan** [comment] 2019-05-17 14:03
1. There is not 1 branding setup for birthday messages so its logical these aren't set...
2. Bug in reinstall https://github.com/our-city-app/mobicage-backend/pull/194

**Comment by bart-at-mobicage** [comment] 2019-06-17 09:14
Probably, when a new app is created the birthday branding isn't automatically created, so I suggest to automate this.

**Comment by RubenMattan** [comment] 2019-06-17 09:18
No its not enabled for any of our apps, so not 1 app has this

**Comment by lucasvanhalst** [comment] 2019-06-19 13:15
can be set here, someone must've removed it
https://gig-mobile-cc.appspot.com/backends/rogerthat_backend/default-settings/brandings/create

**Comment by RubenMattan** [comment] 2019-06-27 07:51
i don't have the birthday branding, so i can't update this

**Comment by bart-at-mobicage** [comment] 2019-06-28 09:15
You can create a new branding using the dashboard with this image

![54047040-45b7f000-41d6-11e9-92d5-bb4d8a3ccbf1](https://user-images.githubusercontent.com/17762105/60331895-f0c30400-9995-11e9-96fd-7d4bb61b83aa.png)

**Comment by RubenMattan** [comment] 2019-09-05 07:51
Uploading a branding is broken...

`ERROR TypeError: Cannot read property 'toString' of undefined
    at Ju.getBackendBrandingFormData (main-es2015.f4528ec38a47154e9690.js:1)
    at Ju.createGlobalBackendBranding (main-es2015.f4528ec38a47154e9690.js:1)
    at c.project (main-es2015.f4528ec38a47154e9690.js:1)
    at c._next (main-es2015.f4528ec38a47154e9690.js:1)
    at c.next (main-es2015.f4528ec38a47154e9690.js:1)
    at r._next (main-es2015.f4528ec38a47154e9690.js:1)
    at r.next (main-es2015.f4528ec38a47154e9690.js:1)
    at Object.next (main-es2015.f4528ec38a47154e9690.js:1)
    at c._next (main-es2015.f4528ec38a47154e9690.js:1)
    at c.__tryOrUnsub (main-es2015.f4528ec38a47154e9690.js:1)`

**Comment by lucasvanhalst** [comment] 2019-09-05 11:56
@RubenMattan should be fixed

**Comment by RubenMattan** [comment] 2019-09-05 12:08
@lucasvanhalst did you deploy the fix?

**Comment by lucasvanhalst** [comment] 2019-09-05 12:15
Yes

**Comment by RubenMattan** [comment] 2019-09-05 12:17
In that case, the issue is nog fixed

**Comment by lucasvanhalst** [comment] 2019-09-05 15:08
How about now @RubenMattan

**Comment by RubenMattan** [comment] 2019-09-05 16:03
Its fixed :-)

**Closed** 2019-09-17 12:29 UTC
Labels: priority_major, state_verification, type_bug
