### ISSUE TITLE
Failed to update events from google

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#193] opened 2017-01-25 07:44 UTC
```python

00:31:44.234
Queue: default
deferred.run(solutions.common.bizz.events.update_events_from_google,
             users.User(email='bart.flex.1@mobicage.com'),
             5757334940811264L)
00:31:44.273
access_token is expired. Now: 2017-01-24 23:31:44.272970, token_expiry: 2016-02-23 17:56:15
00:31:44.273
access_token_expired: True
```

After refreshing the access token we get a 404

When i access the url via a browser i get

```js

{
  error: {
    errors: [
      {
        domain: "usageLimits",
        reason: "dailyLimitExceededUnreg",
        message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
        extendedHelp: "https://code.google.com/apis/console"
      }
    ],
    code: 403,
    message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
   }
}

```

**Comment by siddiquagig** [comment] 2017-03-23 06:39
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2020-01-16 12:44 UTC
Labels: priority_major, type_bug
