### ISSUE TITLE
Agenda branding: multi-date event with different hours not shown well

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#83] opened 2016-11-18 08:53 UTC
Eg. event "Kerstavond" in Gemeente Laarne.
* has 2 different dates
* has 2 different start and end times

In the event list, only the first date is shown
In the detail view, only the start hours are shown

**Comment by siddiquagig** [comment] 2017-03-23 07:49
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2017-10-05 09:23 UTC
Labels: type_feature
