### ISSUE TITLE
Pictures in e-shop doesn't appear

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#489] opened 2017-08-29 12:33 UTC
Pleas see screenshots
90% of the time when we doe a demo the uploaded pictures in the e-shop doesn't appear.

![image](https://user-images.githubusercontent.com/23034120/29821082-f9dcf9f2-8cc6-11e7-96a4-5f43f6805c43.png)

![schermafbeelding 2017-08-29 om 14 32 48](https://user-images.githubusercontent.com/23034120/29821091-046956cc-8cc7-11e7-85fc-705434236083.png)

![schermafbeelding 2017-08-29 om 14 32 59](https://user-images.githubusercontent.com/23034120/29821098-07186aa2-8cc7-11e7-8de9-dab29b272e84.png)

**Comment by bart-at-mobicage** [comment] 2017-08-29 12:49
@OSATOM, both on iOS and Android or only Android?

**Comment by OSATOM** [comment] 2017-08-29 13:58
both

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-08-29 14:49 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by abom** [comment] 2017-09-14 15:31
Duplicate of #540 and https://github.com/rogerthat-platform/rogerthat-android-client/issues/236

**Comment by abom** [comment] 2017-09-14 15:31
Duplicate of #540 and https://github.com/rogerthat-platform/rogerthat-android-client/issues/236

**Closed by abom** 2017-09-14 15:31 UTC
Labels: priority_minor, type_bug
