### ISSUE TITLE
City cannot accept/deny signups via the app

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1217] opened 2019-01-25 08:27 UTC
Reported by service-a79d577a-39ff-41b5-b479-862f429f4694@rogerth.at

**Comment by lucasvanhalst** [comment] 2019-01-25 09:06
cannot reproduce, @stevendepaepe do you have more info? When did it happen?

**Comment by lucasvanhalst** [comment] 2019-01-25 09:12
Last signup of that service was Nov. 19 so whatever it was its probably fixed now

**Closed** 2019-02-12 08:55 UTC
Labels: priority_major, type_bug
