### ISSUE TITLE
window - Scan - Tablet

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#79] opened 2016-11-17 13:07 UTC
When you turnover the tablet the scan-window-preview on the tablet is incorrect.
Still at the left top-corner and scan-image is up-side-down.

**Comment by siddiquagig** [comment] 2017-03-23 07:49
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2017-07-25 11:20 UTC
Labels: state_verification, type_bug
