### ISSUE TITLE
Export customers - group by language

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#192] opened 2017-01-24 15:09 UTC
In the shop, we have to update the "export customers" functionality to group them by language (if it's an excel doc, create a sheet per language)

**Comment by siddiquagig** [comment] 2017-03-23 06:40
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2017-05-12 07:13 UTC
Labels: state_verification, type_feature
