### ISSUE TITLE
group chat

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#55] opened 2016-11-10 14:40 UTC
you can not leave a group chat

**Comment by siddiquagig** [comment] 2017-03-23 07:51
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-11-09 13:55
duplicate of https://github.com/our-city-app/oca-backend/issues/13

**Closed by RubenMattan** 2017-11-09 13:55 UTC
