### ISSUE TITLE
Back Button in Dashboard Communities

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#532] opened 2017-09-13 08:40 UTC
When cities go to their "dashboard" then go to "Services" then go to a "dashboard of a service" - they cannot go back to their "city-dashboard" - they have to login all over again.

This should be solved.
Thanks
![schermafbeelding 2017-09-13 om 10 37 52](https://user-images.githubusercontent.com/23034120/30367866-c642ba78-986f-11e7-84e5-509ef62847cd.png)

**Comment by RubenMattan** [comment] 2017-09-13 08:42
duplicate of https://github.com/our-city-app/oca-backend/issues/467

**Closed by RubenMattan** 2017-09-13 08:42 UTC
Labels: priority_minor, type_feature, type_question
