### ISSUE TITLE
reminder emails

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#213] opened 2017-02-14 08:59 UTC
We get to many complains about the reminder emails.
Can we stop them or make it more visible to unsubscribe.

Thanks

**Comment by siddiquagig** [comment] 2017-03-23 06:37
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Closed** 2018-11-19 14:10 UTC
Labels: type_feature
