### ISSUE TITLE
customermap displays care-institutions as communityservices 

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#151] opened 2016-12-13 09:43 UTC
https://rogerth.at/customers/map/be-edegem?lat=51.157415&lon=4.432333&zoom=13

![schermafbeelding 2016-12-13 om 10 41 51](https://cloud.githubusercontent.com/assets/23034120/21135130/000dad7a-c121-11e6-9fcd-16e122d96b91.png)

**Comment by bart-at-mobicage** [comment] 2017-01-09 14:21
Please check if the organization types of those customers are configured correctly. See the customer detail page. The organization type on this page needs to be the same as the one on the service tab.

**Comment by OSATOM** [comment] 2017-01-10 08:43
In the shop the customer is "Care"
![schermafbeelding 2017-01-10 om 09 07 58](https://cloud.githubusercontent.com/assets/23034120/21799378/470e110c-d719-11e6-815b-a914901bf4b6.png)

**Comment by siddiquagig** [comment] 2017-03-23 06:42
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-03-23 07:53
Create a new icon for emergency services

in customer_map.js add emergency services as well

**Closed** 2017-05-12 07:13 UTC
Labels: priority_minor, state_verification, type_bug
