### ISSUE TITLE
When creating an spanish merchant automatically select spain and spanish

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#278] opened 2017-03-15 09:40 UTC
https://docs.greenitglobe.com/gig/proj_actives/issues/8

**Comment by siddiquagig** [comment] 2017-03-19 06:20
Can we have a ETC of this issue so we can update.

**Comment by siddiquagig** [comment] 2017-03-27 06:10
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2017-03-30 14:53 UTC
Labels: state_verification, type_feature
