### ISSUE TITLE
export_customers_csv doesn't work anymore

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#270] opened 2017-03-13 13:29 UTC
The process is being terminated because it's using too much memory, we'll have to refactor the way it wokrs

**Comment by siddiquagig** [comment] 2017-03-23 06:14
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Closed** 2017-03-30 14:53 UTC
Labels: state_verification, type_bug
