### ISSUE TITLE
Agenda branding: End hour not shown for multi-date events

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#82] opened 2016-11-18 08:44 UTC
In the events detail screen

**Comment by siddiquagig** [comment] 2017-03-23 07:49
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2020-02-19 08:13 UTC
Labels: type_feature
