### ISSUE TITLE
Failed to upload static content PDF

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#257] opened 2017-03-08 07:48 UTC
url: /common/static_content/pdf/post
```python
Caught exception while cleaning context
Traceback (most recent call last):
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/rpc/context.py", line 24, in _safe
    return f(*args, **kwargs)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/rpc/rpc.py", line 308, in wait_for_rpcs
    rpc_items.finalize()
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/rogerthat/rpc/rpc.py", line 237, in finalize
    deferred.defer(defered_func, *args)
  File "/base/data/home/apps/s~mobicagecloudhr/25.399672659706105388/add_1_monkey_patches.py", line 254, in _new_deferred_defer
    return _old_deferred_defer(f, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 280, in defer
    key = _DeferredTaskEntity(data=pickled).put()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 1077, in put
    return datastore.Put(self._entity, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 622, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1879, in __put_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1369, in check_rpc_success
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
RequestTooLargeError: The request to API call datastore_v3.Put() was too large.
```

**Comment by siddiquagig** [comment] 2017-03-23 06:11
Hi,
Can we have a ETC of this issue so we can update.

If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Comment by abom** [comment] 2017-05-31 10:39
Should be fixed when rogerthat-platform/rogerthat-backend#190 is done.

**Closed** 2017-06-16 12:11 UTC
Labels: state_verification, type_bug
