### ISSUE TITLE
Fix needed for events with ridiculously lots of dates

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#459] opened 2017-08-22 12:27 UTC
This events has 1000+ dates: http://www.uitinvlaanderen.be/agenda/e/Inschrijving+Kadens+Diksmuide+muziek+jongvolwassenen+18-24j/408af0dd-63d5-43e4-9b34-e1eff6a74fef

There are a few of those events in Diksmuide which cause that the app_data became bigger than 1Mb, so the capi call can not be sent to the phones.

**Comment by RubenMattan** [comment] 2018-01-24 08:36
Duplicate of #296

**Closed** 2018-01-24 08:36 UTC
Labels: priority_minor, process_duplicate, type_bug
