### ISSUE TITLE
Customize texts on each of the message flow screens in the merchant apps

### ISSUE THREAD

**Issue by FastGeert** [our-city-app/oca-backend#156] opened 2016-12-15 13:43 UTC
Make it possible to do more customization.

**Comment by lucasvanhalst** [comment] 2017-01-20 12:27
- [ ] Ask question

**Comment by siddiquagig** [comment] 2017-03-23 06:41
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2019-01-11 13:19 UTC
Labels: type_feature
