### ISSUE TITLE
OSA Terminal: Show EURO sign when redeeming points/stamps/...

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#60] opened 2016-11-10 14:51 UTC

**Comment by siddiquagig** [comment] 2017-03-23 07:51
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Closed** 2019-01-11 13:19 UTC
