### ISSUE TITLE
In orders (contracts) NIF/CIF should be changed to IVA

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#277] opened 2017-03-15 09:40 UTC
https://docs.greenitglobe.com/gig/proj_actives/issues/9

**Comment by abdulgig** [comment] 2017-03-15 11:00
Also, please let us know the ETA so that the customer can be updated accordingly.

Thanks,

**Comment by siddiquagig** [comment] 2017-03-27 06:10
Hi Bart..

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Comment by bart-at-mobicage** [comment] 2017-04-10 08:24
ActiveS says:
> Now NIF/CIF is changed everywhere for IVA. I attach a screenshot with the explanation

We need to make a distinction between `vat_number` and `vat_percent`.

**Comment by abom** [comment] 2017-04-10 09:26
A screenshot.

![screenshot from 2017-04-10 11-25-42](https://cloud.githubusercontent.com/assets/511438/24854985/7b9a6a48-1de0-11e7-9799-3b91dd1e446c.png)

**Closed** 2017-04-10 12:08 UTC
Labels: priority_critical, state_verification, type_feature
