### ISSUE TITLE
News Via App

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#199] opened 2017-01-30 08:56 UTC
When you take a picture and don't want to use that one and try to make another one the app crashes.

Thanks

**Comment by abom** [comment] 2017-02-08 16:11
@OSATOM On the android/IOS app or what? the step of creating a news item? if so, i cannot reproduce it.

**Comment by siddiquagig** [comment] 2017-03-23 06:38
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Closed** 2017-07-11 11:49 UTC
Labels: priority_major
