### ISSUE TITLE
AppStore promotion video

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#133] opened 2016-12-05 13:32 UTC
In iTunesConnect we can upload a promotion video. Maybe we can upload the videos which are made for Lochristi, Herzele...

**Comment by RubenMattan** [comment] 2016-12-05 15:41
On the play store you can do the same

**Comment by siddiquagig** [comment] 2017-03-23 06:43
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Closed** 2017-10-05 10:30 UTC
Labels: type_feature
