### ISSUE TITLE
VAT validation for Spain.

### ISSUE THREAD

**Issue by FastGeert** [our-city-app/oca-backend#157] opened 2016-12-15 13:44 UTC
In the shop sales people in Spain should be able to validate the VAT numbers of new customers.

**Comment by siddiquagig** [comment] 2017-03-23 06:41
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-03-23 07:29
duplicate https://github.com/our-city-app/oca-backend/issues/157

**Comment by bart-at-mobicage** [comment] 2017-03-23 07:32
#279 is about temporarily disabling the validate button. I think this ticket is about pre-filling all company details based on the VAT number. Correct, @FastGeert ?

**Comment by RubenMattan** [comment] 2017-03-23 07:34
The goal of the change request was to allow Spanish VAT numbers...

**Comment by RubenMattan** [comment] 2017-03-23 07:35
So create a new issue for this temporary fix instead of renaming it

**Comment by RubenMattan** [comment] 2017-03-23 07:40
New issue https://github.com/our-city-app/oca-backend/issues/291

**Closed by RubenMattan** 2017-03-23 07:40 UTC
Labels: process_duplicate, type_feature
