### ISSUE TITLE
Vat validate for Spanish clients

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#154] opened 2016-12-14 12:46 UTC
Is it possible the have a "VALIDATE" VAT check for Spanish VAT numbers
![schermafbeelding 2016-12-14 om 13 45 37](https://cloud.githubusercontent.com/assets/23034120/21182496/b6f10a68-c203-11e6-9847-2dc047f990c7.png)

**Comment by siddiquagig** [comment] 2017-03-23 06:42
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-03-23 07:26
related to https://github.com/our-city-app/oca-backend/issues/279

**Closed** 2017-03-23 07:38 UTC
Labels: process_duplicate, type_feature
