### ISSUE TITLE
Paper loyaly card news updates

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#92] opened 2016-11-22 08:23 UTC
Please make possible that loyalty-card users receive the messages/News by email that our merchants broadcast and not only ones a week.

Thanks

client request of one of our believers
Please reply to stephanie.***@telenet.be (service-beeff08d-b2e6-415e-b998-***@rogerth.at) with the following link:
https://rogerth.at/internal/shop/questions

Title:
doorkrijgen mails

Description:
Beste,
Heb onlangs een bericht uitgezonden onder 'nieuws' met daarin een pdf (onze feestfolder) nu blijkt dat klanten die een fysieke kaart gebruiken (en dus niet de smartphone en dat zijn er heel wat bij ons) deze mail niet doorkrijgen. Hoe kunnen deze klanten die mail wel ontvangen?

**Comment by siddiquagig** [comment] 2017-03-23 07:48
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment] 2017-07-14 10:16
@FastGeert Do you want this feature?

**Comment by RubenMattan** [comment] 2017-07-14 11:24
Geert told me to wait until we had a chat with Tom about this

**Comment by RubenMattan** [comment] 2017-07-14 13:08
Update:

1. Customer scans his paper card at the merchant.
2. After loyalty finished a popup will be shown "do you want news updates" (only show this once)

**Comment by RubenMattan** [comment] 2017-07-14 13:09
Design needs to be made by a designer (also think about attachments etc...)

**Comment by OSATOM** [comment] 2017-08-22 08:19
Can somebody explain this to me?

Thanks

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-07-14 15:08 GMT+02:00 Ruben Mattan <notifications@github.com>:

**Comment by RubenMattan** [comment] 2017-08-23 06:10
We need the design of the email containing the news item (think about all functionality of the news items)

**Closed** 2017-10-23 09:22 UTC
Labels: process_wontfix, state_question, type_feature
