### ISSUE TITLE
Error when opening dashboard of disabled services

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#872] opened 2018-05-03 12:08 UTC
```
2018-05-03 13:24:44.001 CEST
Request identity: service-cf7051e5-5a6c-464d-820f-8909cefee2b8@rogerth.at - xxx (xxx via shop) (WEB) (/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/rogerthat/rpc/users.py:178)

2018-05-03 13:24:45.438 CEST
Expected an integer id or string name as argument 2; received None (a NoneType). (/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/solutions/flex/handlers.py", line 316, in get
    default_app = get_app(customer.app_id)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/rogerthat/bizz/app.py", line 78, in get_app
    return trans() if db.is_in_transaction() else db.run_in_transaction(trans)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2635, in RunInTransactionOptions
    function, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2710, in _RunInTransactionInternal
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2748, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/rogerthat/bizz/app.py", line 73, in trans
    app = App.get(App.create_key(app_id))
  File "/base/data/home/apps/e~rogerthat-server/20180502t152350.409435869469686393/rogerthat/models/__init__.py", line 197, in create_key
    return db.Key.from_path(App.kind(), app_id)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/c5586dbb532f7e5f_unzipped/python27_lib/versions/1/google/appengine/api/datastore_types.py", line 527, in from_path
    'received %r (a %s).' % (i + 2, id_or_name, typename(id_or_name)))
BadArgumentError: Expected an integer id or string name as argument 2; received None (a NoneType).

```

**Comment by RubenMattan** [comment] 2018-05-08 08:40
duplicate of https://github.com/our-city-app/oca-backend/issues/473

**Closed by RubenMattan** 2018-05-08 08:40 UTC
Labels: priority_minor, type_bug
