### ISSUE TITLE
Error in cropper

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#567] opened 2017-09-27 15:42 UTC
```
description: Caught exception in global scope: Uncaught TypeError: imageElem.cropper(...).toDataURL is not a function

errorMessage: Uncaught TypeError: imageElem.cropper(...).toDataURL is not a function
 in https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js at line 179:9
TypeError: imageElem.cropper(...).toDataURL is not a function
    at HTMLButtonElement.<anonymous> (https://dashboard.onzestadapp.be/static/js/solutions/sln-settings.js:1291:72)
    at HTMLButtonElement.dispatch (https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:5:13940)
    at HTMLButtonElement.jQuery.event.dispatch (https://dashboard.onzestadapp.be/static/js/solutions/sln-utils.js:176:33)
    at HTMLButtonElement.v.handle (https://dashboard.onzestadapp.be/static/js/jquery-1.10.0.min.js:5:10677)

mobicageVersion: web

occurenceCount: 5

platform: 0

platformVersion: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

**Comment by RubenMattan** [comment] 2018-05-08 08:46
duplicate of https://github.com/our-city-app/oca-backend/issues/359

**Closed by RubenMattan** 2018-05-08 08:46 UTC
Labels: priority_minor, type_bug
